name: Gotify Server
version: "0.0.10"
slug: addon_gotify
description: Self-hosted notification server (Gotify) as a Home Assistant addon
startup: services
boot: auto
url: https://github.com/OptimusGREEN/ha-addons-dev/tree/main/addon_gotify
webui: "http://[HOST]:[PORT:80]/"
ingress: false
panel_icon: mdi:bell-ring
arch:
  - amd64

ports:
  80/tcp: 8080

ports_description:
  80/tcp: Gotify Web UI

map:
  - config:rw
  - ssl:ro
  - share:rw

options:
  port: 80
  username: admin
  password: admin
  allow_registration: false

schema:
  port: int(1,65535)
  username: str
  password: str
  allow_registration: bool